spring.application.name=bank
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

application.jwt.secret=${JWT_SECRET}
application.jwt.expiration=86400000

resend.api.key=${RESEND_API_KEY}
